### ISSUE TITLE
Update YiiWheels for PHP 5.4+

### ISSUE THREAD

**Issue by tonydspaniard** [2amigos/yiiwheels#129]
After the update for version 2.0 to make it Bootstrap 3+ ready. I plan the following changes to make this library a bit up to date with current PHP versions and standards: 

- [ ] Make use of namespaces and remove those horrible prefixes 
- [ ] Use of composer for the most stable and reliable libraries (ie Boostrap) 
- [ ] Remove YiiStrap dependency (people can make use of YiiWheels independently if its using YiiStrap or not) 
- [ ] New folder structure 

This change, will break B/C. Sorry folks, but is time to move on don't you agree?

**Comment by SamMousa** [comment]
+1

**Comment by tonydspaniard** [comment]
I will be on top of it asap

**Comment by tonydspaniard** [comment]
I was about to upgrade YiiWheels then I thought about the people that are currently using it for Yii1. I cannot do BC and we should focus on Yii2. 

Therefore I am closing this issue as we are already refactoring our site + update our libraries, for their inclusion on the new "wheels" library.
