### ISSUE TITLE
Redactor does not work with  ActiveForm

### ISSUE THREAD

**Issue by alegbebomby** [2amigos/yiiwheels#62]
WhRedactor does not work with ActiveForm, if it does  help  me  out thanks

**Comment by st4nny** [comment]
Hi,
I try to set the field but when I submit the form the attribute and value are not shown in POST array.
I tested the following lines:
<?php $this->widget('yiiwheels.widgets.redactor.WhRedactor', array(
                'model'=>$model
                ,'attribute' => 'desc'
                ,'pluginOptions'=>array(
                    'linebreaks'=>true
                    ,'minHeight' => 150
                )
         )); ?>
         <?php // echo TbHtml::customActiveControlGroup($desc_string, $model, 'desc'); ?>
         <?php // echo $form->customControlGroup($desc_string, $model, 'desc'); ?>
         <?php // echo $form->textArea($model, 'desc'); 
         ?>

and also I try to set the widget as string and to output with customActive/ControlGroup and however the value/attribute is not shown in post array.
The attribute is correctly set in the rules model's in fact with "$form->textArea($model, 'desc')" the value is shown in post array and saved.

Any help? Thanks.
